librarian_model: "gemini/gemini-2.0-flash"
supervisor_model: "openrouter/moonshotai/kimi-k2-thinking"
negative_constraints_model: "openrouter/openai/gpt-oss-20b:free"
permissions_model: "openrouter/openai/gpt-oss-20b:free"
boundaries_model: "openrouter/openai/gpt-oss-20b:free"
docs_dir: "../docs-for-testing"
toc_path: "./artifacts/ToC.json"
artifacts: "./artifacts"
